# Generated by Django 4.1.7 on 2023-10-30 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mwbapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='add_product',
            table='AddProduct',
        ),
        migrations.AlterModelTable(
            name='user',
            table='CompanyUser',
        ),
    ]
